### ISSUE TITLE
dhcp_snooping function broken

### ISSUE THREAD

**Issue by jpobeda** [Cacti/plugin_mactrack#76] opened 2018-05-17 22:44 UTC
At some point, really hard to tell, this got broken. Specifically the IP and MAC collection.

I printed the array_values of 'cdsBindingsIpAddress' and i get

```
Array
(
    [0] => ▒`▒
    [1] => ▒`▒
    [2] => ▒`▒▒
    [3] => ▒`▒▒
    [4] => ▒`▒▒
)
```
cdsBindingsIpAddress gets populated right at the beginning of this function.

`$cdsBindingsIpAddress 	= xform_stripped_oid('.1.3.6.1.4.1.9.9.380.1.4.1.1.4', $device);`

This OID returns Hex-STRING, that's why I apply xform_net_address to it. But it's broken right when cdsBindingsIpAddress gets populated.

I thought i was something with xform_mac_address and/or xform_net_address functions but now I'm thinking it might be something with xform_stripped_oid. Not sure if there were changes made to that function.

Any ideas?

**Comment by jpobeda** [comment] 2018-07-02 21:23
@netniV I think the problem came after a yum update that has updated a whole bunch of php modules included php-snmp and the net-snmp package as well. Does this make sense to you?

Unfortunately I can't downgrade it since packages aren't available. I'll try to reproduce this issue on a new VM with CentOS 7, that'll clarify.

I've got a vm on my laptop with a "similar" setup which I haven't run yum update for a while and tested the latest develop branch and works fine. 

Current Prod server (CentOS 7.4 and Cacti 1.1.38) -> does NOT work

> php-snmp.x86_64                    5.4.16-45.el7            @base

Test VM (CentOS 6.9 and Cacti 1.1.38) -> works

> php-snmp.x86_64        5.3.3-49.el6     @base

This function is mainly calling existing functions such as xform_stripped_oid which calls cacti_snmp_walk.

Any ideas?

What confuses me is that I've put a `print_r(array_values($cdsBindingsIpAddress));` right after it populates the variable and it prints all these funny characters, so only function involved is xform_stripped_oid and of course all the other functions that it calls.

`$cdsBindingsIpAddress   = xform_stripped_oid('.1.3.6.1.4.1.9.9.380.1.4.1.1.4', $device);`

**Comment by jpobeda** [comment] 2018-07-03 00:51
This guy seems to have had a similar issue
https://stackoverflow.com/questions/33237132/php-snmp-returns-strange-hex-values-in-plain-and-object-mode

Found another case
https://stackoverflow.com/questions/30334280/php-snmp-real-walk-returns-bad-characters

Question is, the code hasn't changed so it has to be something else to stop working :S

I Don't think is anything from Cacti core code because I'm running a vm with CentOS 6.9, Cacti 1.1.38 and it works, difference I see is php-snmp package.

I have also installed a new VM with CentOS 7 and php7.1 packages and same issue.

Maybe some defaults on php-snmp have changed?

**Comment by jpobeda** [comment] 2018-07-09 00:10
I ran a simple test using network-weathermap which uses its own functions defined in WeatherMapDataSource_snmpv2c.php and I had the same result but then I changed 

 ` snmp_set_valueretrieval(SNMP_VALUE_PLAIN);`

to 

 ` snmp_set_valueretrieval(SNMP_VALUE_LIBRARY);` 

and it worked.

@cigamit or @netniV any ideas? Even if known were to find it for Cacti I don't think it would be a good idea without knowing the consequences of it.

**Comment by netniV** [comment] 2018-07-09 10:25
So, this function is called within include/vendor/phpsnmp/classSNMP.php in the apply_options() function.  This uses the class's public variable called `valueretrieval`:
```php
snmp_set_valueretrieval($this->valueretrieval);
```

The `valueretrieval` value is set within lib/snmp.php:

```php
if (defined('SNMP_OID_OUTPUT_NUMERIC')) {
        $session->oid_output_format = SNMP_OID_OUTPUT_NUMERIC;
        $session->valueretrieval = SNMP_VALUE_LIBRARY;
}
```

Now this does mean that if the value isn't considered defined, it wouldn't use the SNMP_VALUE_LIBRARY option.  The only real way to know that is to make the system record whether or not it is defined at that point.

**Comment by jpobeda** [comment] 2018-07-10 23:27
@netniV OK, so this is what I found

Changing `$value_output_format` on `cacti_snmp_walk` function from `SNMP_STRING_OUTPUT_GUESS` to `SNMP_STRING_OUTPUT_ASCII` does the trick.
I know this isn't a proper fix, I just get lost following the whole logic, it's too much for my damaged brain.

It seems that this variable gets overwritten or something and the GUESS thing doesn't guess.

I'll keep looking and will add more comments.

If you've got mactrack working and some cisco switches you could reproduce it without having to setup dhcp snooping on your switches. One of the OIDs it walks is for the MAC Addresses and it also comes on HEX format so, if you set a print_r and run it from cli you should be able to see.

On mactrack_cisco.php file
`$dot1dTpFdbEntries[$n] = xform_stripped_oid('.1.3.6.1.2.1.17.4.3.1.1', $device, $snmp_readstring);`

**Comment by netniV** [comment] 2018-07-10 23:37
I was having fun once upon with this too, then I got too busy for MacTrack... https://github.com/Cacti/cacti/issues/1293

There have been some issues with that.  I may have a change to look later this week.

**Comment by jpobeda** [comment] 2018-07-10 23:39
Hey @netniV I found this version of snmp.php before it got broken. I'll keep testing further versions 

https://github.com/Cacti/cacti/commit/e6f62e43955e796fc48cf033d72cb7248e06b56a#diff-38c4468ec62dbb3a480eccbe97af67de

**Comment by jpobeda** [comment] 2018-07-10 23:50
Found it, this commit broke it.

https://github.com/Cacti/cacti/commit/252333336bf84dc382d733b17eafa25adae134d2#diff-38c4468ec62dbb3a480eccbe97af67de

**Comment by jpobeda** [comment] 2018-07-11 00:01
@netniV I think i found the problem on that version, you've set 

```
} elseif ($type == 'walk' && file_exists(read_config_option('path_snmpbulkwalk'))) {
                return SNMP_METHOD_BINARY;
```

Changing it to SNMP_METHOD_PHP fixes it, not sure about the whole logic though.

**Comment by jpobeda** [comment] 2018-07-11 00:29
I've just read https://github.com/Cacti/cacti/issues/1293 comments and noticed you were already on the track.

**Comment by netniV** [comment] 2018-07-11 06:13
The problem is, that was a fixer not a breaker.  The code was wrong as it was trying to check if a file called `path_snmpbulkwalk` existed.  That could never exist (unless someone was doing something really crazy) and should have been reading the configuration option which is under the "Paths" section of the settings.

So, that then leads us to the problem of, why would it be different value when using SNMP_METHOD_PHP rather than BINARY?

**Comment by TheWitness** [comment] 2020-10-25 14:15
Pretty sure that this is fixed now.

**Comment by TheWitness** [comment] 2020-10-25 14:16
Closing this one now.  If it's not fully fixed, open a fresh bug.

**Closed as completed by TheWitness** 2020-10-25 14:16 UTC
