### ISSUE TITLE
Click "Device Tracking" menu, got error

### ISSUE THREAD

**Issue by radiumfu** [Cacti/plugin_mactrack#202] opened 2023-09-17 21:01 UTC
**Describe the bug**
newly installed mactrack plugin, once click "device Tracking" menu button, got error. no page show up

**Expected behavior**
expect to see the mactrack main ui 
![image](https://github.com/Cacti/plugin_mactrack/assets/15271818/49d6562e-3842-400b-8ea4-ce56294b4a25)

**Screenshots the error in cacti log**
![image](https://github.com/Cacti/plugin_mactrack/assets/15271818/1d6c0312-6172-4890-8e74-b7fd8405a5d7)

**Screenshots the error message pop up**
![image](https://github.com/Cacti/plugin_mactrack/assets/15271818/68b40837-61bf-483b-b4d3-3aaa6a590c53)

**Plugin (please complete the following information):**
 - Version: [4.2]
 - Source: [https://github.com/Cacti/plugin_mactrack/archive/refs/tags/v4.2.tar.gz]
 - Identifer: [e.g. apt/yum package name or github commit ref]

**Desktop**
 - OS: [Windows 11]
 - Browser [Edge]
 - Version [117.0.2045.31]

**Server**
 - Ubuntu 22.04.3 LTS
 -  Cacti 1.2.25
 -  PHP 8.1.2-1ubuntu2.14
 - db 10.6.12-MariaDB-0ubuntu0.22.04.1
 - Poller SPINE 1.2.20
 - poller interval 30
 
**Additional context**

**Comment by xmacan** [comment] 2024-03-05 20:17
cannot reproduce on actual 4.6 version, please update

**Comment by xmacan** [comment] 2024-04-19 18:37
no feedback, problem with old version. Closing

**Closed as completed by xmacan** 2024-04-19 18:37 UTC
