### ISSUE TITLE
QA: Avoid use of strlen() and some light PSR 7a0a625 breaks mactrack 

### ISSUE THREAD

**Issue by jdcoats** [Cacti/plugin_mactrack#225] opened 2024-06-17 16:32 UTC
```
2024/06/17 09:22:51 - MACTRACK ERROR: Site not found in database. Can not continue.
2024/06/17 09:22:51 - MACTRACK ERROR: Site not found in database. Can not continue.
2024/06/17 09:22:51 - MACTRACK ERROR: Site not found in database. Can not continue.
```

**Comment by TheWitness** [comment] 2024-06-17 17:45
Should be fixed now.

**Comment by jdcoats** [comment] 2024-06-17 19:25
```
2024/06/17 15:24:00 - CMDPHP ERRORS DETECTED - DISABLING PLUGIN 'mactrack'
2024/06/17 15:24:00 - CMDPHP PHP ERROR Backtrace: (CactiShutdownHandler())
2024/06/17 15:24:00 - ERROR PHP ERROR in Plugin 'mactrack': Uncaught ValueError: substr_count(): Argument #2 ($needle) cannot be empty in /var/www/localhost/htdocs/cacti/plugins/mactrack/lib/mactrack_functions.php:345 Stack trace: #0 /var/www/localhost/htdocs/cacti/plugins/mactrack/lib/mactrack_functions.php(345): substr_count('.1.3.6.1.4.1.9....', '') #1 /var/www/localhost/htdocs/cacti/plugins/mactrack/mactrack_scanner.php(161): find_scanning_function(Array, Array) #2 {main} thrown in file: /var/www/localhost/htdocs/cacti/plugins/mactrack/lib/mactrack_functions.php on line: 345
```

**Comment by jdcoats** [comment] 2024-06-18 15:44
@xxconn & @TheWitness okay so now we have this
```
2024/06/18 11:41:00 - CMDPHP PHP ERROR WARNING Backtrace: (/plugins/mactrack/mactrack_utilities.php[88]:mactrack_display_run_status(), /plugins/mactrack/mactrack_utilities.php[248]:CactiErrorHandler())
2024/06/18 11:41:00 - ERROR PHP WARNING in Plugin 'mactrack': Trying to access array offset on value of type null in file: /var/www/localhost/htdocs/cacti/plugins/mactrack/mactrack_utilities.php on line: 248
```

**Comment by TheWitness** [comment] 2024-06-19 11:18
Awesome Dan.  Thanks for confirming.

**Comment by TheWitness** [comment] 2024-06-19 11:21
What is the value of mt_collection_timing in your case?

**Comment by xxconn** [comment] 2024-06-19 11:33
I think the value of mt_collection_time is null at the first installation plugin and in PHP 8.1, it may raise this problem.  I don't have PHP 8.1 runtime environment, so I cannot confirm the cause.

**Comment by TheWitness** [comment] 2024-06-19 12:05
So, then we need a check and if null set_config_option() to the default.

Maybe a feature request to set all defaults, but that could be dangerous too.

**Comment by jdcoats** [comment] 2024-06-19 12:08
dont know, it is still broken though, every time it starts a run it disables the plugin

**Comment by TheWitness** [comment] 2024-06-19 12:15
```sql
SELECT * FROM settings WHERE name='mt_collection_timing;`
```

**Comment by jdcoats** [comment] 2024-06-19 12:24
mt_collection_timing | 120   |

**Comment by TheWitness** [comment] 2024-06-19 12:37
Refresh and try again.

**Comment by TheWitness** [comment] 2024-06-19 12:38
Commit here.

https://github.com/Cacti/plugin_mactrack/commit/d51e6f5e1986a4c9366e538ccfee4ac8ec80415d

**Comment by jdcoats** [comment] 2024-06-19 12:52
okay next run time in 40min

**Comment by jdcoats** [comment] 2024-06-19 15:24
looks good now. Thanks!

**Comment by xxconn** [comment] 2024-06-20 01:54
When I modify the code like this, I will show blank value in 'Poller Frequency' and write the error log:

2024-06-20 09:26:17 - CMDPHP PHP ERROR WARNING Backtrace: (/plugins/mactrack/mactrack_utilities.php[88]:mactrack_display_run_status(), /plugins/mactrack/mactrack_utilities.php[248]:CactiErrorHandler())
2024-06-20 09:26:17 - ERROR PHP WARNING in Plugin 'mactrack': Undefined array key 7200 in file: /usr/share/cacti/plugins/mactrack/mactrack_utilities.php on line: 248

I think the $seconds_offset should be still divided by 60 into minutes to get the right poller frequency.

**Comment by xxconn** [comment] 2024-06-20 02:01
@TheWitness 

How about to change to like the following:

108c108
<       $collection_timing = read_config_option('mt_collection_timing', true);
---
>       $seconds_offset = read_config_option('mt_collection_timing', true);
110,111c110,111
<       if ($collection_timing != 'disabled') {
<               $seconds_offset = $collection_timing * 60;
---
>       if ($seconds_offset != 'disabled') {
>               $seconds_offset = $seconds_offset * 60;
240c240
<       print '<td>' . __('The Device Tracking Poller is:', 'mactrack') . '</td><td>' . ($total_processes > 0 ? __('Running', 'mactrack') : ($collection_timing == 'disabled' ? __('Disabled', 'mactrack') : __('Idle', 'mactrack'))) . '</td>';
---
>       print '<td>' . __('The Device Tracking Poller is:', 'mactrack') . '</td><td>' . ($total_processes > 0 ? __('Running', 'mactrack') : ($seconds_offset == 'disabled' ? __('Disabled', 'mactrack') : __('Idle', 'mactrack'))) . '</td>';
248c248
<       print '<td width=200>' . __('Poller Frequency:', 'mactrack') . '</td><td>' . ($collection_timing == 'disabled' ? __('N/A', 'mactrack') : $mactrack_poller_frequencies[$collection_timing]) . '</td>';
---
>       print '<td width=200>' . __('Poller Frequency:', 'mactrack') . '</td><td>' . ($seconds_offset == 'disabled' ? __('N/A', 'mactrack') : $mactrack_poller_frequencies[$seconds_offset/60]) . '</td>';

**Comment by xxconn** [comment] 2024-06-20 02:28
@jdcoats 

I have modified the new code, you could try it.

**Comment by jdcoats** [comment] 2024-06-20 19:51
looks good, thanks!

**Comment by TheWitness** [comment] 2024-06-20 19:53
Cool!!!

**Closed as completed by TheWitness** 2024-06-20 19:53 UTC
Labels: bug, QA
